# Generated by Django 3.1.6 on 2021-02-10 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='operate_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='text_files'),
        ),
    ]
